s1 = "Prueba"

#DEVUELVE EL NUMERO DE OCURRENCIAS DE UNA SUBCADENA DE TEXTO EN TODA LA CADENA O EN UN RANGO
print(s1.count('a')) 

#INDICA SI LA CADENA DE TEXTO EMPIEZA CON LA SUBCADENA DE TEXTO QUE LE PASAMOS COMO PARAMETRO
print(s1.startswith('P'))

#INDICA SI LA CADENA DE TEXTO ACABA CON LA SUBCADENA DE TEXTO QUE LE PASMAOS COMO PARAMETRO
print(s1.endswith('a'))

#BUSCA LA SUBCADENA PASADA COMO PARAMETRO EN LA CADENA DE TEXTO
print(s1.find('lo'))
