s1 = "Prueba"
s2 = "prueba"
s3 = "  prueba  "
s4 = "Hola Mundo"

#CAPITALIZAR CADENA DE TEXTO
print(s2.capitalize())

#CONVERTIR UN MINUSCULA TODOS LOS CARACTERES DE UNA CADENA
print(s1.lower())

#CONVIERTE TODOS LO CAARACTERES A MAYUSCULA
print(s2.upper())

#SACA LOS ESPACIOS ENTRE EL COMIENZO Y EL FINAL DE LA CADEA
print(s3.strip())

#DIVIDIR LA CADENA DE CARACTERES SEGUN LA CADENA DE CARACTERES PASADO COMO PARAMETRO
print(s4.split(" "))

#INTERCAMBIA LAS MAYUSCULAS POR LAS MINUSULAS Y VICEVERSA
print(s1.swapcase())

#LE PONE TITULO A LA CADENA DE CARACTERES
print(s2.title())

#QUITA LOS ESAPCIOS EN BLANCO DE LA DERECHA
print(s3.rstrip())

#QUITA LOS ESAPCIOS EN BLANCO DE LA IZQUIERDA
print(s3.lstrip())
